pipeline:
  name: go-pipeline-sample
  identifier: gopipelinesample
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: ashravank
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome
                  identifier: Echo_Welcome
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness"
                  description: test
